//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Empresa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Empresa()
        {
            this.tbl_Punto_Emision = new HashSet<tbl_Punto_Emision>();
        }
    
        public int emp_id { get; set; }
        public string emp_ruc { get; set; }
        public string emp_razon_social { get; set; }
        public string emp_nombre_comercial { get; set; }
        public Nullable<bool> emp_obligada_contabilidad { get; set; }
        public string emp_contribuyente_especial { get; set; }
        public string emp_numero_establecimiento { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Punto_Emision> tbl_Punto_Emision { get; set; }
    }
}
