//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Clientes
    {
        public int cli_id { get; set; }
        public string cli_cedula_ruc { get; set; }
        public string cli_nombres { get; set; }
        public string cli_apellidos { get; set; }
        public string cli_direccion { get; set; }
        public string cli_telefono { get; set; }
        public string cli_correo { get; set; }
        public string cli_estado { get; set; }
        public string cli_usuario { get; set; }
    }
}
