//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Punto_Emision
    {
        public int pem_id { get; set; }
        public Nullable<int> pem_emp_id { get; set; }
        public string pem_direccion_ip { get; set; }
        public string pem_punto_emision { get; set; }
    
        public virtual tbl_Empresa tbl_Empresa { get; set; }
    }
}
