//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Usuarios
    {
        public int usu_id { get; set; }
        public string usu_nombre_usuario { get; set; }
        public string usu_contrasena { get; set; }
        public string usu_rol_codigo { get; set; }
        public string usu_estado { get; set; }
    }
}
