//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Arbol
    {
        public int arb_id { get; set; }
        public string arb_codigo { get; set; }
        public string arb_nombre { get; set; }
        public string arb_estado { get; set; }
    }
}
