//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Productos
    {
        public int pro_id { get; set; }
        public string pro_codigo { get; set; }
        public string pro_descripcion { get; set; }
        public Nullable<int> pro_stock_actual { get; set; }
        public Nullable<int> pro_stock_minimo { get; set; }
        public Nullable<decimal> pro_coste { get; set; }
        public Nullable<decimal> pro_precio_venta { get; set; }
        public byte[] pro_imagen { get; set; }
        public string pro_estado { get; set; }
        public Nullable<int> pro_prv_id { get; set; }
        public Nullable<int> pro_fam_id { get; set; }
        public string pro_imagen_path { get; set; }
        public Nullable<decimal> pro_impuesto { get; set; }
        public string pro_codigo_barras { get; set; }
        public string pro_usuario { get; set; }
    
        public virtual tbl_Familias tbl_Familias { get; set; }
        public virtual tbl_Proveedores tbl_Proveedores { get; set; }
    }
}
