//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Proveedores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Proveedores()
        {
            this.tbl_Productos = new HashSet<tbl_Productos>();
        }
    
        public int prv_id { get; set; }
        public string prv_ruc { get; set; }
        public string prv_razon_social { get; set; }
        public string prv_email { get; set; }
        public string prv_direccion { get; set; }
        public string prv_telefono { get; set; }
        public string prv_pagina_web { get; set; }
        public string prv_estado { get; set; }
        public string prv_usuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Productos> tbl_Productos { get; set; }
    }
}
