//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Factura_Detalle
    {
        public int fad_id { get; set; }
        public Nullable<int> fad_fac_id { get; set; }
        public string fad_fac_numero_serie { get; set; }
        public string fad_pro_codigo { get; set; }
        public string fad_pro_descripcion { get; set; }
        public Nullable<decimal> fad_pro_cantidad { get; set; }
        public Nullable<decimal> fad_pro_precio_venta { get; set; }
        public Nullable<decimal> fad_pro_descuento { get; set; }
        public Nullable<decimal> fac_pro_impuesto { get; set; }
    
        public virtual tbl_Factura_Cabecera tbl_Factura_Cabecera { get; set; }
    }
}
